# Generated by Django 2.1.5 on 2019-01-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictweet', '0003_pictweet_tweet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictweet_tweet',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
