# Generated by Django 2.1.5 on 2019-01-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictweet', '0004_pictweet_tweet_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictweet_tweet',
            name='userId',
        ),
    ]
